import React, { useEffect, useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "../../components/Footer";
import Head from "next/head";
import DatosPersonales from "@/components/MiCuenta/DatosPersonales";
import MisCampanas from "@/components/MiCuenta/MisCampanas";
import MisColaboraciones from "@/components/MiCuenta/MisColaboracion";
import MisDatos from "@/components/MiCuenta/MisDatos";
import MisFinanciamientos from "@/components/MiCuenta/MisFinanciamientos";
import Script from "next/script";

const Index = ({ children }) => {
  const [activeComponent, setActiveComponent] = useState(null);

  const renderComponent = (component) => {
    setActiveComponent(component);
  };
  const renderActiveComponent = () => {
    switch (activeComponent) {
      case "DatosPersonales":
        return <DatosPersonales />;
      case "MisCampanas":
        return <MisCampanas />;
      case "MisColaboraciones":
        return <MisColaboraciones />;
      case "MisFinanciamientos":
        return <MisFinanciamientos />;
      default:
        return null;
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          src="https://kit.fontawesome.com/73d94b16ae.js"
          crossorigin="anonymous"
          defer
        ></Script>
      </Head>
      <div className="min-h-screen flex flex-col justify-between ">
        <Navbar />

        <div style={{ display: "flex", marginTop: "100px" }}>
          <div>
            <MisDatos renderComponent={renderComponent} data={data} />
          </div>
          <div style={{ flex: 4 }}>{renderActiveComponent()}</div>
        </div>

        <main className="w-[95%]  sm:w-[90%] md:w-[90%] mx-auto  lg:w-[85%]  lg:max-w-[1240px]  lg:mx-auto  ">
          {children}
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Index;
