import React from "react";
import Navbar from "@/components/Navbar";
import Footer from "../Footer";
import Head from "next/head";

const Layout = ({ children }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script
          src="https://kit.fontawesome.com/73d94b16ae.js"
          crossorigin="anonymous"
        ></script>
      </Head>
      <div className="min-h-screen flex flex-col justify-between ">
        <Navbar />
        <main className="w-[95%]  sm:w-[90%] md:w-[90%] mx-auto  lg:w-[85%]  lg:max-w-[1240px]  lg:mx-auto  ">
          {children}
        </main>
        <Footer />
      </div>
    </div>
  );
};

export default Layout;
