import Head from "next/head";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Banner from "@/components/Banner";
import SliderMoveCard from "@/components/sliderMoveCard/SliderMoveCard";
import SliderDestacCard from "@/components/sliderDestacCard/SliderDestacCard";
import TestimonioEslider from "@/components/testimonio/TestimonioEslider";
import Onboarding from "@/components/Onboarding/Onboarding";
import MisDatos from "@/components/MiCuenta/MisDatos";
import Banner2 from "@/components/Banner2";
import axios from "axios";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });
export default function Home({ order, proy, users }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <Script
          src="https://kit.fontawesome.com/73d94b16ae.js"
          crossorigin="anonymous" defer
        ></Script>
      </Head>
      <Navbar users={users} />
      <Banner2 />
      <div className="flex justify-around flex-wrap"></div>
      <Onboarding />
      <main className="  w-[95%]  sm:w-[90%] md:w-[80%] lg:w-[85%]   m-auto ">
        <div className="relative">
          <h2 className="font-bold   text-2xl sm:text-3xl lg:text-4xl  text-text font-Kanit my-4">
            NOVEDADES
          </h2>
          <SliderMoveCard proy={proy} />
        </div>
        <div className="relative">
          <h2 className="font-bold     text-2xl  sm:text-4xl text-text font-Kanit my-4">
            PROYECTOS DESTACADOS
          </h2>
          <SliderDestacCard data={order} />
        </div>
        <TestimonioEslider />
      </main>
      <Footer />
      <MisDatos />
    </>
  );
}

export async function getStaticProps() {
  const [project, user] = await Promise.all([
    await axios.get(`${process.env.BACK_URL}api/projects`),
    await axios.get(`${process.env.BACK_URL}api/users/profile`),
  ]);
  const projects = project.data;
  const users = user.data;
  const order = projects.sort(
    (a, b) => b.parcialAmount / b.totalAmount - a.parcialAmount / a.totalAmount
  );
  const proy = projects.slice(projects.length - 4, projects.length);

  return {
    props: {
      order,
      proy,
      users,
    },
  };
}
